@Simex_HostAddress = https://localhost:7073

GET {{Simex_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Simex_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testCliente",
  "password": "Test1234"
}


###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjciLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdENsaWVudGUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0Y2xpZW50ZTFAcHJpbWVsb2dpc3RpY3MuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ0xJRU5URSIsImV4cCI6MTc3NzkxMDk4OCwiaXNzIjoiU2ltZXguQXBpIiwiYXVkIjoiU2ltZXguTW9iaWxlIn0.mUEgo_jcxPI25ARLifQFA0ioKciy_VMrFzvCCRB66UI
###
GET {{Simex_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}
Accept: application/json
###


GET {{Simex_HostAddress}}/api/operations/recent
Authorization: Bearer {{token}}
Accept: application/json
###

@operationId=9
POST {{Simex_HostAddress}}/api/operations/{{operationId}}/reject
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "reason": "Cliente no acepta la propuesta"
}
###

POST {{Simex_HostAddress}}/api/operations/{{operationId}}/accept
Authorization: Bearer {{token}}
Accept: application/json
###

GET {{Simex_HostAddress}}/api/operations/user-operations
Authorization: Bearer {{token}}
Accept: application/json
###

GET {{Simex_HostAddress}}/api/operations/all-operations
Authorization: Bearer {{token}}
Accept: application/json
###
